project:
  type: website
  output-dir: docs
  
website:
  title: "NORA MÜLLER"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
      - cv.qmd
      - media.qmd
      - contact.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Nora Müller"

format:
  html:
    theme: lux
    toc: true

editor: source

