project:
  type: website
  output-dir: docs
  
website:
  title: "NORA MÜLLER"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
      - cv.qmd
      - media.qmd
      - contact.qmd
    right: 
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.de/citations?user=4aBRE7gAAAAJ&hl=de
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0002-0756-0188
      - text: "{{< ai osf >}}"
        href: https://osf.io/jk48r/
      - text: "{{< ai researchgate >}}"
        href: https://www.researchgate.net/profile/Nora-Mueller-3
    tools:
      - icon: github
        href: https://github.com/nrmllr




  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Nora Müller"

format:
  html:
    theme: lux
    toc: true

editor: source



