---
title: "Publications"
---

## Articles in peer-reviewed and indexed journals

* Alexandra Wicht, **Nora Müller**, and Reinhard Pollak. 2024. 'Gendered Wage Returns to Changes in Non-routine Job Tasks: Evidence from Germany' *Research in Social Stratification and Mobility* 100963. [doi.org/10.1016/j.rssm.2024.100963](https://doi.org/10.1016/j.rssm.2024.100963)

* Jascha Dräger, Klaus Pforr, and **Nora Müller**. 2023. 'Why Net Worth Misrepresents Wealth Effects and What to Do About It' *Sociological Science* 10 534-558. [doi.org/10.15195/v10.a19](https://doi.org/10.15195/v10.a19) [Open access]

* **Müller, Nora**, Klaus Pforr, and Jascha Dräger. 2023. 'Wealth stratification and the insurance function of wealth' (Editorial) *Social inclusion* 11 (1): 128-134. [doi.org/10.17645/si.v11i1.6680](https://doi.org/10.17645/si.v11i1.6680) [Open access]

* **Müller, Nora**, Klaus Pforr, and Oshrat Hochman. 2021. 'Double Burden? Implications of indebtedness to general life satisfaction following negative life events in international comparison' *Journal of European Social Policy* 31 (5): 614–628. [doi.org/10.1177/09589287211050505](https://doi.org/10.1177/09589287211050505) [Open access]

> The above paper is part of a [Special Issue on 'Social Policy and Wealth'](https://journals.sagepub.com/toc/espa/31/5) edited by Ive Marx and Brian Nolan.

* **Müller, Nora**, Nico Stawarz, and Alexandra Wicht. 2021. 'Who experiences subjective job insecurity due to digital transformation in Germany?' *Soziale Welt* 72 (4): 614–628. [doi.org/10.5771/0038-6073-2021-4-384](https://doi.org/10.5771/0038-6073-2021-4-384) [Restricted access] [Download accepted version](files/Mueller_etal_2021_Soziale_Welt_accepted_version.pdf) [Replication files](https://doi.org/10.7802/2303)

* **Müller, Nora**, Klaus Pforr, and Oshrat Hochman. 2020. 'The non-linear relationship between parental wealth and children’s post-secondary transitions in Germany' *Soziale Welt* 71 (3): 268-307. [doi.org/10.5771/0038-6073-2020-3-268](https://doi.org/10.5771/0038-6073-2020-3-268) [Restricted access] [Download accepted version](files/Mueller_etal_2020_SozialeWelt_accepted_version.pdf) [Replication files](https://doi.org/10.7802/2073)

* Dräger, Jascha, and **Nora Müller**. 2020. 'Wealth stratification in the early school career in Germany' *Research in Social Stratification and Mobility* 67 100483. [doi.org/10.1016/j.rssm.2020.100483](https://doi.org/10.1016/j.rssm.2020.100483)

* **Müller, Nora**, and Jascha Dräger. 2019. 'Economic roles and marriage timing: A cohort comparison between women and men in East and West Germany' *Longitudinal and Life Course Studies* 10 (3): 347-374. [doi.org/10.1332/175795919X1562847468072](https://doi.org/10.1332/175795919X1562847468072)

* Wicht, Alexandra, **Nora Müller**, Simone Haasler, and Alexandra Nonnenmacher. 2019. "The interplay between education, skills and job quality" *Social Inclusion* 7 (3): 347-374. [doi.org/10.17645/si.v7i3.2052](https://doi.org/10.17645/si.v7i3.2052)

* **Skopek, Nora**, Sandra Buchholz, and Hans-Peter Blossfeld. 2014. 'National patterns of income and wealth inequality' *International Journal of Comparative Sociology* 55 (6): 463-488. [doi.org/10.1177/0020715214565674](https://doi.org/10.1177/0020715214565674)

* Kolb, Kathrin, **Nora Skopek**, Sandra Buchholz, and Hans-Peter Blossfeld. 2013. 'The two dimensions of housing inequality in Europe: Are high home ownership rates an indicator for low housing values?' *Comparative Population Studies* 38 (4): 1009-1040. [doi.org/10.1007/s11609-012-0185-0](https://doi.org/10.1007/s11609-012-0185-0) 

* **Skopek, Nora**, Kathrin Kolb, Sandra Buchholz, and Hans-Peter Blossfeld. 2013. 'Einkommensreich – vermögensarm? Die Zusammensetzung von Vermögen und die Bedeutung einzelner Vermögenskomponenten im europäischen Vergleich' [Income-rich—asset-poor? The composition of wealth and the meaning of different wealth components in a European comparison] *Berliner Journal für Soziologie* 22 (2): 163-187. [doi.org/10.12765/CPoS-2013-22en](https://doi.org/10.12765/CPoS-2013-22en) [An English version is included as 'Chapter 03' in my [dissertation](https://fis.uni-bamberg.de/handle/uniba/21740)]

## Working papers and preprints

* Wicht, Alexandra, **Nora Müller**, Reinhard Pollak, and Silke Anger. 2023. 'Gendered wage effects of changes in job tasks: Evidence from Germany.' *SocArXiv*. [doi.org/10.31235/osf.io/5dcgw](https://doi.org/10.31235/osf.io/5dcgw)

* Bles, Per, **Nora Müller**, and Lynn-Malou Lutz. 2023. 'Do country-level characteristics affect adults’ level of ICT skills? A European comparison with a two-component measure of ICT skills.' *SocArXiv*. [doi.org/10.31235/osf.io/hbndk](https://doi.org/10.31235/osf.io/hbndk)

* Pietrolucci, Andrea, Jascha Dräger, **Nora Müller**, and Marco Albertini. 2023. 'Wealth gaps in post-secondary enrolment in Europe? A comparison across European countries and wealth components.' *SocArXiv*. [doi.org/10.31235/osf.io/7ywg5](https://doi.org/10.31235/osf.io/7ywg5)

* Bles, Per, Ineke Bijlsma, Marie-Christine Fregin, Tomas Korpi, Mark Levels, Lynn-Malou Lutz, **Nora Müller**, Giampiero Passaretta, Reinhard Pollak, Rolf Van der Velden, Heike Solga, and Raymond Montizaan. 2021. 'Preparing today's youths for tomorrow's labour market: Analysis of the relationship between initial education and skills acquisition accross countries and over time.' *Technequality Working Paper Series* 2021/8. [Link](https://www.technequality-project.eu/files/d33fdsystemsandrequirementsv1022-12-1921pdf)

* Dräger, Jascha, Klaus Pforr, and **Nora Müller**. 2021. 'Wealth 2D – An alternative approach to explore wealth effects.' SocArXiv. [doi.org/10.31235/osf.io/zk72e](https://doi.org/10.31235/osf.io/zk72e)

* **Müller, Nora**, Klaus Pforr, and Oshrat Hochman. 2017. 'The Effect of Parental Wealth on Children’s Educational Decisions in Germany: Compensation or Demotivation?' SocArXiv. [doi.org/10.31235/osf.io/c46za](https://doi.org/10.31235/osf.io/c46za)

## Articles in edited volumes

* Hochman, Oshrat, **Nora Müller**, and Klaus Pforr. 2019. Debts, negative life events and subjective well-being: disentangling relationships, In *Wealth(s) and subjective well-being*, edited by Gäel Brulé, and Christian Suter, Social Indicators Research Series 76, 377-399. Cham: Springer. [doi.org/10.1007/978-3-030-05535-6_17](https://doi.org/10.1007/978-3-030-05535-6_17)

* **Skopek, Nora**. 2016. Sozialwissenschaftliche Methodenausbildung für Postgraduierte im deutschen und internationalen Kontext, In *Human Resources: Qualitätsaspekte der Ausbildung in der empirischen Forschung*, edited by Christian König, Matthias Stahl, and Erich Wiegand, Schriftenreihe der ASI - Arbeitsgemeinschaft Sozialwissenschaftlicher Institute, 153-166. Wiesbaden: Springer Fachmedien.  [doi.org/10.1007/978-3-658-12568-4_11](https://doi.org/10.1007/978-3-658-12568-4_11)

* **Skopek, Nora**. 2014. Vermögen in Europa, In *Reichtum, Philanthropie und Zivilgesellschaft*, edited by Wolfgang Lauterbach, Michael Hartmann, and Miriam Ströing, 47–76. Wiesbaden: Springer. [url](http://link.springer.com/chapter/10.1007%2F978-3-658-06013-8_3)



## Mongraphs

* **Skopek, Nora**. 2015. *Wealth as a distinct dimension of social inequality.* Bamberger Beiträge zur Soziologie 14. Bamberg: University of Bamberg Press [url](https://opus4.kobv.de/opus4-bamberg/frontdoor/index/index/docId/26552)

> This is my dissertation thesis. It includes [...].

* **Müller, Nora**. 2010. *Erwerbseintritt und "Timing" der Ehe: eine längsschnittliche Untersuchung der Bedeutung des Erwerbseintritts von Frauen für den Zeitpunkt der ersten Eheschließung.* Diplomarbeit. Bamberg: Otto-Friedrich-Universität Bamberg. [url](https://nbn-resolving.org/urn:nbn:de:0168-ssoar-456849)

> This is my master thesis. It includes [...]. An updated and shortened version of it has been published as: 
* **Müller, Nora**, and Jascha Dräger. 2019. 'Economic roles and marriage timing: A cohort comparison between women and men in East and West Germany' *Longitudinal and Life Course Studies* 10 (3): 347-374. [doi.org/10.1332/175795919X1562847468072](https://doi.org/10.1332/175795919X1562847468072)





